(() => {
  "use strict";
  const Q = window.KANKEN_QUESTIONS || [];
  const I = window.KANKEN_IDIOMS || [];
  const K = window.KANKEN_JUKUGO_KUN || [];
  const R = window.KANKEN_RELATIONS || [];
  const KEY = "suminote-v2";
  const defaults = {route:"home",settings:{mode:"priority"},progress:{},history:[],favorites:[],memos:{},session:null};
  let state = load();
  let selectedCount = 10;
  let selectedKind = "reading";
  let attemptText = "";
  let kunAttemptText = "";
  const PAGE_SIZE = 20;
  let listView = {type:"dictionary",query:"",filter:"all",category:"all",page:1};
  const IDIOM_HIDDEN_READINGS = {"和光同塵":"どうじん","道聴塗説":"とせつ","意気軒昂":"けんこう","気宇壮大":"そうだい","豪放磊落":"らいらく","不羈奔放":"ほんぽう","剛毅木訥":"ぼくとつ","温故知新":"ちしん","切磋琢磨":"たくま","臥薪嘗胆":"しょうたん","魯魚亥豕":"がいし","奔逸絶塵":"ぜつじん","春蛙秋蝉":"しゅうぜん","城狐社鼠":"しゃそ","浮花浪蕊":"ろうずい","円木警枕":"けいちん","道傍苦李":"くり","鳩首凝議":"ぎょうぎ","輪廻転生":"てんしょう","捲土重来":"ちょうらい","規矩準縄":"じゅんじょう","天神地祇":"ちぎ","欣喜雀躍":"じゃくやく","鎧袖一触":"いっしょく","紫電一閃":"いっせん","牽強附会":"ふかい","啐啄同時":"どうじ","虚心坦懐":"たんかい","鵬程万里":"ばんり","甜言蜜語":"みつご","天佑神助":"しんじょ","街談巷説":"こうせつ","孟母断機":"だんき","獅子奮迅":"ふんじん","阿附迎合":"げいごう","情緒纏綿":"てんめん","赤手空拳":"くうけん","蚊虻走牛":"そうぎゅう","前途遼遠":"りょうえん","百尺竿頭":"かんとう","周章狼狽":"ろうばい","寸指測淵":"そくえん","燃眉之急":"のきゅう","張三李四":"りし","允文允武":"いんぶ","虎尾春氷":"しゅんぴょう","一蓮托生":"たくしょう","氷肌玉骨":"ぎょっこつ","嘉言善行":"ぜんこう","鳥面鵠形":"こくけい","朝蠅暮蚊":"ぼぶん","綾羅錦繍":"きんしゅう","暮色蒼然":"そうぜん","四面楚歌":"そか","亡羊補牢":"ほろう","抜山蓋世":"がいせい","不倶戴天":"たいてん","不惜身命":"しんみょう","君子豹変":"ひょうへん","千篇一律":"いちりつ"};
  const IDIOM_READING_PARTS = {"同塵":["どう","じん"],"塗説":["と","せつ"],"軒昂":["けん","こう"],"壮大":["そう","だい"],"磊落":["らい","らく"],"奔放":["ほん","ぽう"],"木訥":["ぼく","とつ"],"知新":["ち","しん"],"琢磨":["たく","ま"],"嘗胆":["しょう","たん"],"亥豕":["がい","し"],"絶塵":["ぜつ","じん"],"秋蝉":["しゅう","ぜん"],"社鼠":["しゃ","そ"],"浪蕊":["ろう","ずい"],"警枕":["けい","ちん"],"苦李":["く","り"],"凝議":["ぎょう","ぎ"],"転生":["てん","しょう"],"重来":["ちょう","らい"],"準縄":["じゅん","じょう"],"地祇":["ち","ぎ"],"雀躍":["じゃく","やく"],"一触":["いっ","しょく"],"一閃":["いっ","せん"],"附会":["ふ","かい"],"同時":["どう","じ"],"坦懐":["たん","かい"],"万里":["ばん","り"],"蜜語":["みつ","ご"],"神助":["しん","じょ"],"巷説":["こう","せつ"],"断機":["だん","き"],"奮迅":["ふん","じん"],"迎合":["げい","ごう"],"纏綿":["てん","めん"],"空拳":["くう","けん"],"走牛":["そう","ぎゅう"],"遼遠":["りょう","えん"],"竿頭":["かん","とう"],"狼狽":["ろう","ばい"],"測淵":["そく","えん"],"之急":["の","きゅう"],"李四":["り","し"],"允武":["いん","ぶ"],"春氷":["しゅん","ぴょう"],"托生":["たく","しょう"],"玉骨":["ぎょく","こつ"],"善行":["ぜん","こう"],"鵠形":["こく","けい"],"暮蚊":["ぼ","ぶん"],"錦繍":["きん","しゅう"],"蒼然":["そう","ぜん"],"楚歌":["そ","か"],"補牢":["ほ","ろう"],"蓋世":["がい","せい"],"戴天":["たい","てん"],"身命":["しん","みょう"],"豹変":["ひょう","へん"],"一律":["いち","りつ"]};
  const IDIOM_SOUND_KANJI = {"どう":"同動堂道銅導","じん":"塵人仁陣刃甚","と":"塗途都徒渡斗","せつ":"説節雪設切拙","けん":"軒剣健兼研堅","こう":"昂高公光工功","そう":"壮走相総草創","だい":"大台代題第内","らい":"磊来雷頼礼莱","らく":"落楽絡洛酪烙","ほん":"奔本翻反凡品","ぽう":"放方法砲邦芳","ぼく":"木僕墨牧朴睦","とつ":"訥突凸咄杜津","ち":"知地智治値置","しん":"新心真神信進","たく":"琢宅卓拓託沢","ま":"磨魔摩麻真馬","しょう":"嘗勝称賞掌商","たん":"坦胆担単端短","がい":"亥害外街概蓋","し":"豕四志士史市","ぜつ":"絶舌設節拙雪","しゅう":"秋州周修衆秀","ぜん":"蝉善全前然禅","しゃ":"社者車舎謝斜","そ":"鼠祖素訴粗蘇","ろう":"浪郎朗老廊牢","ずい":"蕊随髄瑞粋遂","けい":"警形計景軽系","ちん":"枕沈珍陳鎮賃","く":"苦区句駆久玖","り":"李里理利梨璃","ぎょう":"凝行業仰暁尭","ぎ":"議義技儀疑宜","てん":"転天点展典店","ちょう":"重長張町鳥超","じゅん":"準順純潤巡淳","じょう":"縄上場常情城","じゃく":"雀弱若寂着酌","やく":"躍薬役約訳厄","いっ":"一逸溢壱佚乙","しょく":"触食職色植飾","せん":"閃千線戦選船","ふ":"附不府富符布","かい":"会回海界階解","じ":"時字事治持次","ばん":"万番板晩盤蛮","みつ":"蜜密満光充三","ご":"語五後護誤御","じょ":"助女序除徐如","だん":"断段団男談暖","き":"機気期器基紀","ふん":"奮粉分紛憤墳","げい":"迎芸鯨倪睨猊","ごう":"合号豪剛郷業","めん":"綿面免麺棉緬","くう":"空孔功宮腔倥","ぎゅう":"牛牛仇求宮久","りょう":"遼両良量領涼","えん":"遠円園縁延炎","かん":"竿官管刊寒幹","とう":"頭東当塔等投","ばい":"狽倍売梅陪培","そく":"測速側則足束","の":"之乃野埜能濃","きゅう":"急久旧球救究","いん":"允印因員院引","ぶ":"武部舞侮無蕪","しゅん":"春俊瞬旬駿峻","ぴょう":"氷評表票標漂","ぎょく":"玉局曲極旭欲","こつ":"骨忽滑乞壺克","こく":"鵠国刻告穀酷","ぼ":"暮母墓簿慕模","ぶん":"蚊文分聞紋雰","きん":"錦金近勤琴均","か":"歌家科花火果","ほ":"補保歩穂捕舗","せい":"世正生制成星","たい":"戴体対帯隊泰","みょう":"命名明妙冥銘","ひょう":"豹表票標評氷","へん":"変辺編片偏遍","いち":"一市位置壱逸","りつ":"律率立栗列陸"};

  const app = document.querySelector("#app");
  const backButton = document.querySelector("#backButton");
  const bottomNav = document.querySelector("#bottomNav");
  const settingsButton = document.querySelector("#settingsButton");
  const brandButton = document.querySelector("#brandButton");
  const modalRoot = document.querySelector("#modalRoot");

  function load(){try{return merge(defaults,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return structuredClone(defaults)}}
  function merge(base,data){return {...base,...data,settings:{...base.settings,...data.settings},progress:data.progress||{},history:data.history||[],favorites:data.favorites||[],memos:data.memos||{}}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
  function getQ(id){return Q.find(q=>q.id===id)}
  function jukugoKunEntry(q,type){return type==='jukugo'?{id:q.id+'-jukugo',word:q.word,reading:q.reading,meaning:q.meaning,category:'熟語の読み',source:q.source,verified:q.verified}:{id:q.id+'-kun',word:q.kunWord,reading:q.kunReading,accepted:q.kunAccepted,okurigana:q.okurigana,hintLength:q.hintLength,meaning:q.meaning,category:'一字訓読み',source:q.source,verified:q.verified}}
  function getAnyQ(id){const direct=Q.find(q=>q.id===id)||I.find(q=>q.id===id)||K.find(q=>q.id===id)||R.find(q=>q.id===id);if(direct)return direct;const match=String(id).match(/^(k\d+)-(jukugo|kun)$/);if(!match)return null;const base=K.find(q=>q.id===match[1]);return base?jukugoKunEntry(base,match[2]):null}
  function normalize(v){return v.trim().replace(/[ァ-ヶ]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x60)).replace(/\s+/g,"")}
  function normalizeReading(v){const kana=String(v).normalize("NFKC").replace(/[ァ-ヶ]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x60));return (kana.match(/[ぁ-ゖゝゞ]/g)||[]).join("")}
  function route(name){state.route=name;save();render();window.scrollTo({top:0,behavior:"smooth"})}
  function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),1800)}
  function stats(){const p=Object.values(state.progress);return {seen:p.length,weak:p.filter(x=>x.weak).length,correct:state.history.filter(x=>x.correct).length}}
  function layout(){const sub=!['home','history','dictionary'].includes(state.route);backButton.classList.toggle('hidden',!sub);bottomNav.style.display=['quiz','cover','result'].includes(state.route)?'none':'grid';document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route))}

  function render(){layout();({home:renderHome,setup:renderSetup,cover:renderCover,quiz:renderQuiz,result:renderResult,history:()=>renderList('history'),dictionary:()=>renderList('dictionary'),settings:renderSettings}[state.route]||renderHome)();app.focus({preventScroll:true})}
  function renderHome(){const s=stats();app.innerHTML=`<section class="screen"><div class="hero"><p class="eyebrow">KANJI KENTEI STUDY</p><h1>漢検準一級 問題集</h1></div>${state.session?`<div class="resume-card"><strong>途中の学習があります</strong><span>${state.session.index+1} / ${state.session.ids.length}問目から再開できます</span><div class="resume-actions"><button class="primary" data-action="resume">続きから</button><button class="secondary" data-action="discard">最初から</button></div></div>`:''}<div class="course-list"><button class="course-card" data-action="setup" data-kind="reading"><small>読み</small><h2>総合</h2><p>一問一答で読みを答える</p></button><button class="course-card hyogai-card" data-action="setup" data-kind="hyogai"><small>読み</small><h2>表外読み</h2><p>常用漢字表にない読みを答える</p></button><button class="course-card idiom-card" data-action="setup" data-kind="idiom"><small>選択問題</small><h2>四字熟語</h2><p>空欄の二字の読みと漢字を選ぶ</p></button><button class="course-card jukugo-kun-card" data-action="setup" data-kind="jukugoKun"><small>二段階・読み問題</small><h2>熟語と一字訓</h2><p>熟語の読みと一字の訓読みを答える</p></button><button class="course-card relation-card" data-action="setup" data-kind="relation"><small>選択問題</small><h2>対義語・類義語</h2><p>関係する語と意味を覚える</p></button></div><h2 class="section-title">学習記録</h2><div class="stat-row"><div class="stat"><b>${s.seen}</b><span>学習済み</span></div><div class="stat"><b>${s.weak}</b><span>苦手</span></div><div class="stat"><b>${s.correct}</b><span>累計正解</span></div></div><h2 class="section-title">すぐに確認</h2><div class="quick-grid"><button class="quick-card" data-route="history"><span>◷</span><b>過去問</b><small>直近100問</small></button><button class="quick-card" data-route="dictionary"><span>▤</span><b>登録単語</b><small>${dictionaryItems().length}語を収録</small></button></div></section>`}
  function renderSetup(){app.innerHTML=`<section class="screen"><h1 class="session-title">NEW SESSION</h1><div class="panel"><div class="choice-grid">${(selectedKind==='jukugoKun'?[10]:[10,15,20]).map(n=>`<button class="choice ${n===selectedCount?'selected':''}" data-count="${n}">${n}問</button>`).join('')}</div><h2 class="section-title">出題方法</h2><div class="segmented"><button data-mode="random" class="${state.settings.mode==='random'?'active':''}">完全ランダム</button><button data-mode="priority" class="${state.settings.mode==='priority'?'active':''}">苦手・未出題優先</button></div><button class="primary wide start-button" data-action="start">表紙へ進む</button></div></section>`}
  function weight(q){if(state.settings.mode==='random')return 100;const p=state.progress[q.id];return !p?115:p.weak?105:100}
  function pick(count){const source=selectedKind==="idiom"?I:selectedKind==="jukugoKun"?K:selectedKind==="hyogai"?Q.filter(q=>q.category==="表外読み"):selectedKind==="relation"?R:Q;const pool=source.map(q=>({q,key:Math.pow(Math.random(),1/weight(q))}));return pool.sort((a,b)=>b.key-a.key).slice(0,Math.min(count,source.length)).map(x=>x.q.id)}
  function newSession(){state.session={kind:selectedKind,ids:pick(selectedCount),index:0,attempts:0,answered:false,correct:null,part:selectedKind==="jukugoKun"?"jukugo":selectedKind==="idiom"?"reading":"word",wordCorrect:null,choiceOrders:{},relationChoice:null,relationLocked:false,relationCorrect:null,relationReadingCorrect:null,answers:[],startedAt:Date.now()};save();route('cover')}
  function renderCover(){const titles={reading:'総合',hyogai:'表外読み',idiom:'四字熟語',jukugoKun:'熟語と一字訓',relation:'対義語<br>類義語'},formats={reading:'読み',hyogai:'読み',idiom:'選択',jukugoKun:'読み',relation:'選択'};app.innerHTML=`<section class="cover"><button class="cover-book" data-action="open-book"><h1>${titles[state.session.kind]||'総合'}</h1><p>${state.session.ids.length}問・${formats[state.session.kind]||'読み'}</p></button><p class="hint">表紙をタップして始める</p></section>`}
  function current(){return state.session&&getAnyQ(state.session.ids[state.session.index])}
  function readingWord(q){if(!q.target)return q.hintLength&&q.okurigana?`<span class="word-with-hint"><span class="kanji-stack"><span class="reading-circles" aria-label="送り仮名を除く読みは${q.hintLength}文字">${Array.from({length:q.hintLength},()=>"<i></i>").join("")}</span><span>${esc(q.word.slice(0,-q.okurigana.length))}</span></span><span class="okurigana">${esc(q.okurigana)}</span></span>`:esc(q.word);const at=q.word.indexOf(q.target),before=q.word.slice(0,at),after=q.word.slice(at+q.target.length);return `<span class="phrase-question">${esc(before)}<span class="kanji-stack"><span class="reading-circles" aria-label="表外読みは${q.hintLength||Array.from(q.reading).length}文字">${Array.from({length:q.hintLength||Array.from(q.reading).length},()=>"<i></i>").join("")}</span><span class="reading-target">${esc(q.target)}</span></span>${esc(after)}</span>`}
  function renderQuiz(){const s=state.session,q=current();if(!s||!q){route('home');return}if(s.kind==='idiom'){renderIdiomQuiz();return}if(s.kind==='jukugoKun'){renderJukugoKunQuiz();return}if(s.kind==='relation'){renderRelationQuiz();return}const pct=((s.index+1)/s.ids.length)*100;const accepted=[q.reading,...(q.accepted||[])];app.innerHTML=`<section class="quiz-screen"><div class="progress-head"><span></span><span>${s.index+1} / ${s.ids.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div><article class="paper-card reading-paper"><div class="question-number">第${s.index+1}問</div><div class="question-word">${readingWord(q)}</div><div class="answer-area">${!s.answered?`<label for="answerInput">ひらがなで入力　入力可能回数 ${s.attempts}/2</label><div class="answer-row"><input id="answerInput" value="${esc(attemptText)}" autocomplete="off" autocapitalize="off" inputmode="kana" placeholder="わからない時は空欄で確定"><button class="primary" data-action="answer">回答を送信</button></div><p class="hint">空欄のまま確定すると、答えを表示します。</p>`:`<div class="feedback ${s.correct?'correct':'wrong'}">${s.correct?'○ 正解':'× 不正解'}　正答：${esc(accepted[0])}</div><div class="explanation"><h3>${esc(q.word)} <small>（${esc(q.reading)}）</small></h3><div class="metadata"><span class="tag">${esc(q.category)}</span>${(q.variants||[]).map(v=>`<span class="tag">異体・別表記 ${esc(v)}</span>`).join('')}</div><p>${esc(q.meaning)}</p></div><div class="quiz-tools"><button class="secondary" data-action="favorite">${state.favorites.includes(q.id)?'★ お気に入り':'☆ お気に入り'}</button><button class="primary" data-action="next">${s.index===s.ids.length-1?'結果を見る':'次の問題へ'}</button></div>`}</div></article></section>`;if(!s.answered)setTimeout(()=>document.querySelector('#answerInput')?.focus(),50)}
  function idiomReading(q){return IDIOM_HIDDEN_READINGS[q.word]||q.reading}
  function katakana(v){return String(v).replace(/[ぁ-ゖ]/g,ch=>String.fromCharCode(ch.charCodeAt(0)+0x60))}
  function shuffled(values){return [...values].sort(()=>Math.random()-.5)}
  function idiomKanjiPool(q){const correct=Array.from(q.missing),parts=IDIOM_READING_PARTS[q.missing];if(!parts)return [];const left=[correct[0],...Array.from(IDIOM_SOUND_KANJI[parts[0]]||"")],right=[correct[1],...Array.from(IDIOM_SOUND_KANJI[parts[1]]||"")];const pool=[];for(const a of left)for(const b of right){const word=a+b;if(word!==q.missing&&!pool.includes(word))pool.push(word)}return shuffled(pool).slice(0,7)}
  function idiomChoices(q,part){const s=state.session,key=q.id+"-"+part;if(s.choiceOrders[key])return s.choiceOrders[key];let values;if(part==="reading"){const correct=idiomReading(q),others=I.filter(x=>x.id!==q.id).map(idiomReading).filter((v,i,a)=>v!==correct&&a.indexOf(v)===i);values=[correct,...shuffled(others).slice(0,2)].map(katakana)}else{values=[q.missing,...shuffled(idiomKanjiPool(q)).slice(0,2)]}return s.choiceOrders[key]=shuffled(values)}
  function renderIdiomQuiz(){const s=state.session,q=current(),pct=((s.index+1)/s.ids.length)*100,part=s.part==="word"?"reading":s.part,choices=idiomChoices(q,part),label=part==="reading"?"（〇〇）に入る二字の読みを選んでください":"同じ読みになる二字を選んでください";const options=choices.map((c,i)=>"<button class=\"option-choice\" data-idiom-answer=\""+esc(c)+"\"><span>"+(i+1)+"</span>"+esc(c)+"</button>").join("");s.part=part;save();app.innerHTML="<section class=\"quiz-screen\"><div class=\"progress-head\"><span></span><span>"+(s.index+1)+" / "+s.ids.length+"</span></div><div class=\"progress\"><span style=\"width:"+pct+"%\"></span></div><article class=\"paper-card\"><div class=\"question-number\">第"+(s.index+1)+"問</div><div class=\"question-word idiom-prompt\">"+esc(q.prompt.replace("●●","〇〇"))+"</div><div class=\"answer-area\">"+(!s.answered?"<div class=\"option-list\">"+options+"</div>":"<div class=\"feedback "+(s.correct?"correct":"wrong")+"\">"+(s.correct?"○ 正解！":"× 不正解…")+"　正答："+esc(q.word)+"</div><div class=\"explanation\"><h3>"+esc(q.word)+" <small>（"+esc(q.reading)+"）</small></h3><p>"+esc(q.meaning)+"</p></div><div class=\"quiz-tools\"><button class=\"secondary\" data-action=\"favorite\">"+(state.favorites.includes(q.id)?"★ お気に入り":"☆ お気に入り")+"</button><button class=\"primary\" data-action=\"next\">"+(s.index===s.ids.length-1?"結果を見る":"次の問題へ")+"</button></div>")+"</div></article></section>"}
  function renderRelationQuiz(){const s=state.session,q=current(),pct=((s.index+1)/s.ids.length)*100,label=q.type==='antonym'?'対義語':'類義語',symbol=q.type==='antonym'?'⇔':'≒';s.choiceOrders=s.choiceOrders||{};const choices=s.choiceOrders[q.id]||(s.choiceOrders[q.id]=[...q.choices].sort(()=>Math.random()-.5));app.innerHTML=`<section class="quiz-screen"><div class="progress-head"><span></span><span>${s.index+1} / ${s.ids.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div><article class="paper-card relation-paper"><div class="question-number">第${s.index+1}問</div><div class="question-word relation-prompt">${esc(q.prompt)}</div><div class="relation-question">問：<span class="relation-type ${q.type}">${label}</span>は？</div><div class="answer-area">${!s.answered?`<div class="option-list relation-options">${choices.map((choice,i)=>`<button class="option-choice ${s.relationChoice===choice?'selected':''}" data-relation-choice="${esc(choice)}" ${s.relationLocked?'disabled':''}><span>${i+1}</span>${esc(choice)}<b>${s.relationChoice===choice?(s.relationLocked?'確定':'選択中'):''}</b></button>`).join('')}</div><label class="relation-reading-label" for="relationReadingInput"><span class="relation-reading-head"><b>読み</b><em>入力可能回数 ${s.attempts}/2</em></span><input id="relationReadingInput" value="${esc(attemptText)}" autocomplete="off" inputmode="kana" placeholder="「${esc(q.prompt)}」の読みをひらがなで入力"></label><button class="primary wide relation-submit" data-action="submit-relation">回答を送信</button>`:`<div class="split-feedback relation-feedback"><div class="feedback ${s.relationCorrect?'correct':'wrong'}">${label}　${s.relationCorrect?'○ 正解':'× 不正解'}<small>正答：${esc(q.answer)}</small></div><div class="feedback ${s.relationReadingCorrect?'correct':'wrong'}">上の語の読み　${s.relationReadingCorrect?'○ 正解':'× 不正解'}<small>正答：${esc(q.promptReading)}</small></div></div><div class="explanation"><h3>${esc(q.prompt)} ${symbol} ${esc(q.answer)}</h3><p class="relation-reading-answer">${esc(q.prompt)}（${esc(q.promptReading)}）</p><div class="metadata"><span class="tag">${label}</span></div><p><b>${esc(q.prompt)}</b>：${esc(q.promptMeaning)}</p><p><b>${esc(q.answer)}</b>：${esc(q.answerMeaning)}</p></div><div class="quiz-tools"><button class="secondary" data-action="favorite">${state.favorites.includes(q.id)?'★ お気に入り':'☆ お気に入り'}</button><button class="primary" data-action="next">${s.index===s.ids.length-1?'結果を見る':'次の問題へ'}</button></div>`}</div></article></section>`;if(!s.answered)setTimeout(()=>document.querySelector('#relationReadingInput')?.focus(),50)}
  function selectRelation(value){const s=state.session;if(s.relationLocked)return;const input=document.querySelector('#relationReadingInput');if(input)attemptText=input.value;s.relationChoice=value;save();renderRelationQuiz()}
  function submitRelation(){const s=state.session,q=current(),input=document.querySelector('#relationReadingInput');if(!s||!q||!input)return;if(!s.relationChoice){toast('先に'+(q.type==='antonym'?'対義語':'類義語')+'を選んでください');return}const reading=normalizeReading(input.value);if(!reading){toast('上の大きな語の読みを入力してください');input.focus();return}if(!s.relationLocked){s.relationCorrect=s.relationChoice===q.answer;s.relationLocked=true}s.relationReadingCorrect=reading===normalizeReading(q.promptReading);attemptText=input.value;if(s.relationReadingCorrect){finishQuestion(Boolean(s.relationCorrect),s.relationChoice+'／'+reading);return}if(s.attempts<1){s.attempts++;attemptText='';save();renderRelationQuiz();toast('読みをもう一度入力できます');return}finishQuestion(false,s.relationChoice+'／'+reading)}
  function renderJukugoKunQuiz(){const s=state.session,q=current(),pct=((s.index+1)/s.ids.length)*100,kunDisplay=q.okurigana?`<span class="word-with-hint"><span class="kanji-stack"><span class="reading-circles" aria-label="送り仮名を除く読みは${q.hintLength}文字">${Array.from({length:q.hintLength},()=>'<i></i>').join('')}</span><span>${esc(q.kunWord.slice(0,-q.okurigana.length))}</span></span><span class="okurigana">${esc(q.okurigana)}</span></span>`:esc(q.kunWord),field=(type,label,value,correct)=>{const status=correct?'is-correct':s.answered?'is-wrong':'';return `<label><span>${label}</span><div class="answer-input-wrap ${status}"><input id="${type==='jukugo'?'jukugoInput':'kunInput'}" value="${esc(value)}" autocomplete="off" inputmode="kana" placeholder="ひらがなで入力" ${s.answered||correct?'disabled':''}>${correct?'<b class="inline-judgment">○ 正解</b>':s.answered?'<b class="inline-judgment">× 誤答</b>':''}</div></label>`};app.innerHTML=`<section class="quiz-screen"><div class="progress-head"><span></span><span>${s.index+1} / ${s.ids.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div><article class="paper-card jukugo-kun-paper"><div class="question-number jukugo-question-number">第${s.index+1}問</div><div class="jukugo-kun-pair"><div><strong>${esc(q.word)}</strong></div><b class="pair-arrow">⇔</b><div><strong>${kunDisplay}</strong></div></div><div class="answer-area"><div class="dual-answer-grid">${field('jukugo','① 熟語の読み',attemptText,s.jukugoCorrect)}${field('kun','② 一字訓読み',kunAttemptText,s.kunCorrect)}</div>${!s.answered?`<button class="primary wide dual-submit" data-action="answer-jukugo-kun">回答を送信</button><p class="hint">入力可能回数 ${s.attempts}/2　送り仮名は入力してもしなくても正解になります。</p>`:`<div class="explanation"><h3>① ${esc(q.word)}（${esc(q.reading)}）</h3><p class="kun-answer">② ${esc(q.kunWord)}（${esc(q.kunReading)}）</p><div class="metadata"><span class="tag">熟語の読み</span><span class="tag">一字訓読み</span></div><p>${esc(q.meaning)}</p></div><div class="separate-favorites"><button class="secondary" data-favorite="${q.id}-jukugo">${state.favorites.includes(q.id+'-jukugo')?'★':'☆'} ①熟語を登録</button><button class="secondary" data-favorite="${q.id}-kun">${state.favorites.includes(q.id+'-kun')?'★':'☆'} ②一字訓を登録</button></div><button class="primary wide start-button" data-action="next">${s.index===s.ids.length-1?'結果を見る':'次の問題へ'}</button>`}</div></article></section>`;if(!s.answered)setTimeout(()=>document.querySelector(s.jukugoCorrect?'#kunInput':'#jukugoInput')?.focus(),50)}
  function recordPart(q,part,correct,answer){const item=jukugoKunEntry(q,part),old=state.progress[item.id]||{correct:0,wrong:0};state.progress[item.id]={correct:old.correct+(correct?1:0),wrong:old.wrong+(correct?0:1),weak:!correct,lastSeen:Date.now()};state.history.unshift({id:item.id,correct,answer,at:Date.now()});return {id:item.id,correct,answer}}
  function finishJukugoKun(jukugoCorrect,kunCorrect,jukugoAnswer,kunAnswer){const s=state.session,q=current();s.answered=true;s.correct=jukugoCorrect&&kunCorrect;s.jukugoCorrect=jukugoCorrect;s.kunCorrect=kunCorrect;s.jukugoEvaluated=true;s.kunEvaluated=true;s.answers.push(recordPart(q,'jukugo',jukugoCorrect,jukugoAnswer),recordPart(q,'kun',kunCorrect,kunAnswer));state.history=state.history.slice(0,100);save();renderJukugoKunQuiz()}
  function submitJukugoKun(){const s=state.session,q=current(),jukugoInput=document.querySelector('#jukugoInput'),kunInput=document.querySelector('#kunInput');if(!s||!q||!jukugoInput||!kunInput)return;const jukugoAnswer=normalizeReading(jukugoInput.value),kunAnswer=normalizeReading(kunInput.value),jukugoCorrect=Boolean(s.jukugoCorrect||(jukugoAnswer&&jukugoAnswer===normalizeReading(q.reading))),kunAccepted=[q.kunReading,...(q.kunAccepted||[])].map(normalizeReading),kunCorrect=Boolean(s.kunCorrect||(kunAnswer&&kunAccepted.includes(kunAnswer)));attemptText=jukugoInput.value;kunAttemptText=kunInput.value;s.jukugoCorrect=jukugoCorrect;s.kunCorrect=kunCorrect;s.jukugoEvaluated=true;s.kunEvaluated=true;if(jukugoCorrect&&kunCorrect){finishJukugoKun(true,true,jukugoAnswer,kunAnswer);return}if(s.attempts<1){s.attempts++;save();renderJukugoKunQuiz();return}finishJukugoKun(jukugoCorrect,kunCorrect,jukugoAnswer||'（空欄）',kunAnswer||'（空欄）')}
  function answerIdiom(value){const s=state.session,q=current();if(s.part==="reading"){s.wordCorrect=value===katakana(idiomReading(q));if(!s.wordCorrect){finishQuestion(false,value);toast("× 不正解…");return}s.part="kanji";save();renderIdiomQuiz();toast("○ 正解！");return}const kanjiCorrect=value===q.missing;finishQuestion(Boolean(s.wordCorrect&&kanjiCorrect),katakana(idiomReading(q))+"／"+value);toast(kanjiCorrect?"○ 正解！":"× 不正解…")}
  function submit(){const s=state.session,q=current(),input=document.querySelector('#answerInput');if(!s||!q)return;const answer=normalizeReading(input.value);attemptText=input.value;const accepted=[q.reading,...(q.accepted||[])].map(normalizeReading);if(answer&&accepted.includes(answer)){finishQuestion(true,answer);return}if(!answer){finishQuestion(false,'（スキップ）');return}s.attempts++;if(s.attempts>=2){finishQuestion(false,answer)}else{save();attemptText='';kunAttemptText='';renderQuiz();toast('もう一度入力できます')}}
  function finishQuestion(correct,answer){const s=state.session,q=current();s.answered=true;s.correct=correct;s.answers.push({id:q.id,correct,answer});const old=state.progress[q.id]||{correct:0,wrong:0};state.progress[q.id]={correct:old.correct+(correct?1:0),wrong:old.wrong+(correct?0:1),weak:!correct,lastSeen:Date.now()};state.history.unshift({id:q.id,correct,answer,at:Date.now()});state.history=state.history.slice(0,100);save();attemptText='';renderQuiz()}
  function nextQuestion(){const s=state.session;if(s.index>=s.ids.length-1){route('result');return}s.index++;s.attempts=0;s.answered=false;s.correct=null;s.part=s.kind==='jukugoKun'?'jukugo':s.kind==='idiom'?'reading':'word';s.wordCorrect=null;s.relationChoice=null;s.relationLocked=false;s.relationCorrect=null;s.relationReadingCorrect=null;s.jukugoCorrect=null;s.kunCorrect=null;s.jukugoEvaluated=false;s.kunEvaluated=false;attemptText='';kunAttemptText='';save();renderQuiz()}
  function renderResult(){const s=state.session;if(!s){route('home');return}const answers=s.answers,correct=answers.filter(a=>a.correct).length,pct=Math.round(correct/answers.length*100)||0;app.innerHTML=`<section class="screen"><div class="result-hero"><p class="eyebrow">SESSION COMPLETE</p><div class="score-ring" style="--score:${pct}%"><b>${correct}/${answers.length}</b><span>正答率 ${pct}%</span></div><h1 class="section-title" style="margin:0">おつかれさまでした</h1></div>${answers.some(a=>!a.correct)?`<h2 class="section-title">間違えた問題</h2><div class="word-list">${answers.filter(a=>!a.correct).map(a=>wordItem(getAnyQ(a.id),a)).join('')}</div>`:'<div class="resume-card"><strong>全問正解です</strong><span>見事です。この調子で続けましょう。</span></div>'}<button class="primary wide start-button" data-action="finish">ホームへ戻る</button></section>`}
  function wordItem(q,record){if(!q)return'';const fav=state.favorites.includes(q.id),readingLabel=q.kunWord?`${q.reading} ／ ${q.kunWord} ${q.kunReading}`:q.reading;return `<article class="word-item" data-id="${q.id}"><div class="word-summary"><button class="star" data-favorite="${q.id}" aria-label="お気に入り">${fav?'★':'☆'}</button><button class="word-main" data-toggle="${q.id}" style="border:0;background:none;text-align:left"><b>${esc(q.word)}</b><span>${esc(readingLabel)}</span></button>${record?`<span class="result-mark ${record.correct?'ok':'ng'}">${record.correct?'○':'×'}</span>`:'<span>⌄</span>'}</div><div class="word-detail"><div class="metadata"><span class="tag">${esc(q.category)}</span>${q.source==='study_note'?'<span class="tag">ノート由来</span>':''}${(q.variants||[]).map(v=>`<span class="tag">別表記 ${esc(v)}</span>`).join('')}</div><p>${esc(q.meaning)}</p><label class="hint">自分のメモ</label><textarea class="memo" data-memo="${q.id}" placeholder="覚え方や補足を入力">${esc(state.memos[q.id]||'')}</textarea></div></article>`}
  function renderList(type){const isHistory=type==='history';const title=isHistory?'過去問':'登録単語';listView={type,query:'',filter:'all',category:'all',page:1};app.innerHTML=`<section class="screen"><p class="eyebrow">${isHistory?'RECENT 100':'DICTIONARY'}</p><h1 class="section-title" style="font-size:27px;margin-top:0">${title}</h1><input class="search" id="searchInput" placeholder="漢字・読みから検索"><div class="filters status-filters">${!isHistory?'<button class="filter active" data-filter="all">すべて</button><button class="filter" data-filter="favorite">お気に入り</button><button class="filter" data-filter="weak">苦手</button><button class="filter" data-filter="unseen">未出題</button>':''}</div>${!isHistory?'<div class="category-filter-wrap"><span>分類</span><div class="filters category-filters"><button class="filter active" data-category="all">すべて</button><button class="filter" data-category="hyogai">表外</button><button class="filter" data-category="general">一般読み</button><button class="filter" data-category="idiom">四字熟語</button><button class="filter" data-category="jukugoReading">熟語の読み</button><button class="filter" data-category="singleKun">一字訓読み</button><button class="filter" data-category="antonym">対義語</button><button class="filter" data-category="synonym">類義語</button></div></div>':''}<div id="listCount" class="list-count"></div><nav class="pagination pagination-top" aria-label="ページ（上）"></nav><div id="wordList" class="word-list"></div><nav class="pagination pagination-bottom" aria-label="ページ（下）"></nav></section>`;updateList()}
  function dictionaryItems(){const seen=new Set(),jukugoKun=K.flatMap(q=>[jukugoKunEntry(q,'jukugo'),jukugoKunEntry(q,'kun')]);return [...Q,...I,...jukugoKun,...R].filter(q=>{const key=q.category+'|'+q.word;if(seen.has(key))return false;seen.add(key);return true}).map(q=>({q}))}
  function updateList(){const {type,query,filter,category}=listView,n=normalize(query);let items=type==='history'?state.history.map(h=>({q:getAnyQ(h.id),r:h})):dictionaryItems();items=items.filter(({q})=>q&&(normalize(q.word).includes(n)||normalize(q.reading).includes(n)||normalize(q.kunWord||'').includes(n)||normalize(q.kunReading||'').includes(n)||(q.variants||[]).some(v=>normalize(v).includes(n))));if(type!=='history'){if(filter==='favorite')items=items.filter(x=>state.favorites.includes(x.q.id));if(filter==='weak')items=items.filter(x=>state.progress[x.q.id]?.weak);if(filter==='unseen')items=items.filter(x=>!state.progress[x.q.id]);if(category==='hyogai')items=items.filter(x=>x.q.category==='表外読み');if(category==='general')items=items.filter(x=>['一般読み','熟語'].includes(x.q.category));if(category==='idiom')items=items.filter(x=>x.q.category==='四字熟語');if(category==='jukugoReading')items=items.filter(x=>x.q.category==='熟語の読み');if(category==='singleKun')items=items.filter(x=>x.q.category==='一字訓読み');if(category==='antonym')items=items.filter(x=>x.q.category==='対義語');if(category==='synonym')items=items.filter(x=>x.q.category==='類義語')}const pages=Math.max(1,Math.ceil(items.length/PAGE_SIZE));listView.page=Math.min(listView.page,pages);const start=(listView.page-1)*PAGE_SIZE,pageItems=items.slice(start,start+PAGE_SIZE);document.querySelector('#listCount').textContent=items.length?`全 ${items.length}語　${listView.page} / ${pages}ページ`:'0語';document.querySelector('#wordList').innerHTML=pageItems.length?pageItems.map(x=>wordItem(x.q,x.r)).join(''):`<div class="empty">該当する単語はありません</div>`;const pageNumbers=Array.from({length:pages},(_,i)=>i+1).map(page=>`<button class="page-number ${page===listView.page?'active':''}" data-page="${page}" ${page===listView.page?'aria-current="page"':''}>${page}</button>`).join('');document.querySelectorAll('.pagination').forEach(el=>el.innerHTML=pages>1?`<button data-page="${listView.page-1}" ${listView.page===1?'disabled':''}>← 前へ</button><div class="page-numbers">${pageNumbers}</div><button data-page="${listView.page+1}" ${listView.page===pages?'disabled':''}>次へ →</button>`:'')}
  function renderSettings(){app.innerHTML=`<section class="screen"><p class="eyebrow">OPTIONS</p><h1 class="section-title" style="font-size:27px;margin-top:0">オプション</h1><div class="panel"><div class="setting-row"><label>出題方法</label><p>次回の学習セットから反映されます。</p><div class="segmented"><button data-mode="random" class="${state.settings.mode==='random'?'active':''}">完全ランダム</button><button data-mode="priority" class="${state.settings.mode==='priority'?'active':''}">苦手・未出題優先</button></div></div><div class="setting-row"><label>出題の重み</label><p>通常 100 ／ 苦手 105 ／ 未出題 115</p></div><div class="setting-row"><label>この端末の学習データ</label><p>履歴・お気に入り・メモ・進行中の問題を消去します。</p><button class="danger" data-action="reset">学習データを消去</button></div></div></section>`}
  function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();toast(state.favorites.includes(id)?'お気に入りに追加しました':'お気に入りから外しました')}
  function showDiscard(){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>途中の学習を終了しますか？</h2><p>現在の問題セットは削除されます。確定済みの回答履歴は残ります。</p><div class="modal-actions"><button class="secondary" data-modal="close">キャンセル</button><button class="danger" data-modal="discard">終了する</button></div></div></div>`}
  document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.route)route(t.dataset.route);if(t.dataset.count){selectedCount=Number(t.dataset.count);renderSetup()}if(t.dataset.mode){state.settings.mode=t.dataset.mode;save();render()}if(t.dataset.action==='setup'){selectedKind=t.dataset.kind||'reading';selectedCount=10;route('setup')};if(t.dataset.action==='start')newSession();if(t.dataset.action==='open-book')route('quiz');if(t.dataset.action==='answer')submit();if(t.dataset.action==='answer-jukugo-kun')submitJukugoKun();if(t.dataset.idiomAnswer)answerIdiom(t.dataset.idiomAnswer);if(t.dataset.relationChoice)selectRelation(t.dataset.relationChoice);if(t.dataset.action==='submit-relation')submitRelation();if(t.dataset.action==='next')nextQuestion();if(t.dataset.action==='resume')route('quiz');if(t.dataset.action==='discard'){state.session=null;save();render()}if(t.dataset.action==='favorite')toggleFavorite(current().id);if(t.dataset.action==='finish'){state.session=null;save();route('home')}if(t.dataset.action==='reset'){if(confirm('学習データをすべて消去しますか？')){localStorage.removeItem(KEY);state=structuredClone(defaults);route('home')}}if(t.dataset.favorite)toggleFavorite(t.dataset.favorite);if(t.dataset.toggle)t.closest('.word-item').classList.toggle('open');if(t.dataset.filter){document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===t));listView.filter=t.dataset.filter;listView.page=1;updateList()}if(t.dataset.category){document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x===t));listView.category=t.dataset.category;listView.page=1;updateList()}if(t.dataset.page){listView.page=Number(t.dataset.page);updateList();window.scrollTo({top:0,behavior:'smooth'})}if(t.dataset.modal==='close')modalRoot.innerHTML='';if(t.dataset.modal==='discard'){modalRoot.innerHTML='';state.session=null;save();route('home')}});
  document.addEventListener('input',e=>{if(e.target.id==='searchInput'){listView.query=e.target.value;listView.page=1;updateList()}});
  document.addEventListener('change',e=>{if(e.target.dataset.memo){state.memos[e.target.dataset.memo]=e.target.value;save();toast('メモを保存しました')}});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&['answerInput','jukugoInput','kunInput','relationReadingInput'].includes(e.target.id)){e.preventDefault();state.session?.kind==='jukugoKun'?submitJukugoKun():state.session?.kind==='relation'?submitRelation():submit()}});
  backButton.addEventListener('click',()=>{if(state.route==='quiz'&&state.session){showDiscard();return}route('home')});brandButton.addEventListener('click',()=>route('home'));settingsButton.addEventListener('click',()=>route('settings'));
  render();
})();








