(() => {
  "use strict";
  const Q = window.KANKEN_QUESTIONS || [];
  const I = window.KANKEN_IDIOMS || [];
  const KEY = "suminote-v2";
  const defaults = {route:"home",settings:{mode:"priority"},progress:{},history:[],favorites:[],memos:{},session:null};
  let state = load();
  let selectedCount = 10;
  let selectedKind = "reading";
  let attemptText = "";

  const app = document.querySelector("#app");
  const backButton = document.querySelector("#backButton");
  const bottomNav = document.querySelector("#bottomNav");
  const settingsButton = document.querySelector("#settingsButton");
  const brandButton = document.querySelector("#brandButton");
  const modalRoot = document.querySelector("#modalRoot");

  function load(){try{return merge(defaults,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return structuredClone(defaults)}}
  function merge(base,data){return {...base,...data,settings:{...base.settings,...data.settings},progress:data.progress||{},history:data.history||[],favorites:data.favorites||[],memos:data.memos||{}}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function esc(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
  function getQ(id){return Q.find(q=>q.id===id)}
  function getAnyQ(id){return Q.find(q=>q.id===id)||I.find(q=>q.id===id)}
  function normalize(v){return v.trim().replace(/[ァ-ヶ]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x60)).replace(/\s+/g,"")}
  function route(name){state.route=name;save();render();window.scrollTo({top:0,behavior:"smooth"})}
  function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),1800)}
  function stats(){const p=Object.values(state.progress);return {seen:p.length,weak:p.filter(x=>x.weak).length,correct:state.history.filter(x=>x.correct).length}}
  function layout(){const sub=!['home','history','dictionary'].includes(state.route);backButton.classList.toggle('hidden',!sub);bottomNav.style.display=['quiz','cover','result'].includes(state.route)?'none':'grid';document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route))}

  function render(){layout();({home:renderHome,setup:renderSetup,cover:renderCover,quiz:renderQuiz,result:renderResult,history:()=>renderList('history'),dictionary:()=>renderList('dictionary'),settings:renderSettings}[state.route]||renderHome)();app.focus({preventScroll:true})}
  function renderHome(){const s=stats();app.innerHTML=`<section class="screen"><div class="hero"><p class="eyebrow">KANJI KENTEI STUDY</p><h1>一字ずつ、<br>確かな知識に。</h1><p>漢検準1級の読みを、紙の単語帳のように。</p></div>${state.session?`<div class="resume-card"><strong>途中の学習があります</strong><span>${state.session.index+1} / ${state.session.ids.length}問目から再開できます</span><div class="resume-actions"><button class="primary" data-action="resume">続きから</button><button class="secondary" data-action="discard">最初から</button></div></div>`:''}<div class="course-list"><button class="course-card" data-action="setup" data-kind="reading"><small>読み問題</small><h2>漢検 準一級</h2><p>ひらがなで読みを答える</p></button><button class="course-card idiom-card" data-action="setup" data-kind="idiom"><small>選択問題</small><h2>四字熟語</h2><p>空欄の二字と意味を選ぶ</p></button></div><h2 class="section-title">学習記録</h2><div class="stat-row"><div class="stat"><b>${s.seen}</b><span>学習済み</span></div><div class="stat"><b>${s.weak}</b><span>苦手</span></div><div class="stat"><b>${s.correct}</b><span>累計正解</span></div></div><h2 class="section-title">すぐに確認</h2><div class="quick-grid"><button class="quick-card" data-route="history"><span>◷</span><b>過去問</b><small>直近100問</small></button><button class="quick-card" data-route="dictionary"><span>▤</span><b>登録単語</b><small>${Q.length}語を収録</small></button></div></section>`}
  function renderSetup(){app.innerHTML=`<section class="screen"><p class="eyebrow">NEW SESSION</p><h1 class="section-title" style="font-size:27px;margin-top:0">${selectedKind==="idiom"?"四字熟語を何問、学習しますか？":"何問、学習しますか？"}</h1><div class="panel"><div class="choice-grid">${(selectedKind==="idiom"?[10]:[10,15,20]).map(n=>`<button class="choice ${n===selectedCount?'selected':''}" data-count="${n}">${n}問</button>`).join('')}</div><h2 class="section-title">出題方法</h2><div class="segmented"><button data-mode="random" class="${state.settings.mode==='random'?'active':''}">完全ランダム</button><button data-mode="priority" class="${state.settings.mode==='priority'?'active':''}">苦手・未出題優先</button></div><button class="primary wide start-button" data-action="start">表紙へ進む</button></div><p class="hint">同じ学習セット内で、同じ問題は重複しません。</p></section>`}
  function weight(q){if(state.settings.mode==='random')return 100;const p=state.progress[q.id];return !p?115:p.weak?105:100}
  function pick(count){const source=selectedKind==="idiom"?I:Q;const pool=source.map(q=>({q,key:Math.pow(Math.random(),1/weight(q))}));return pool.sort((a,b)=>b.key-a.key).slice(0,Math.min(count,Q.length)).map(x=>x.q.id)}
  function newSession(){state.session={kind:selectedKind,ids:pick(selectedCount),index:0,attempts:0,answered:false,correct:null,part:"word",wordCorrect:null,answers:[],startedAt:Date.now()};save();route('cover')}
  function renderCover(){app.innerHTML=`<section class="cover"><button class="cover-book" data-action="open-book"><h1>${state.session.kind==="idiom"?"四字熟語":"漢検準一級"}</h1><p>${state.session.ids.length}問・${state.session.kind==="idiom"?"選択":"読み"}</p></button><p class="hint">表紙をタップして始める</p></section>`}
  function current(){return state.session&&getAnyQ(state.session.ids[state.session.index])}
  function renderQuiz(){const s=state.session,q=current();if(!s||!q){route('home');return}if(s.kind==='idiom'){renderIdiomQuiz();return}const pct=((s.index+1)/s.ids.length)*100;const accepted=[q.reading,...(q.accepted||[])];app.innerHTML=`<section class="quiz-screen"><div class="progress-head"><span>第 ${s.index+1} 問</span><span>${s.index+1} / ${s.ids.length}</span></div><div class="progress"><span style="width:${pct}%"></span></div><article class="paper-card"><div class="question-label">次の語の読みを答えてください</div><div class="question-word">${esc(q.word)}</div><div class="answer-area">${!s.answered?`<label for="answerInput">ひらがなで入力（${s.attempts+1}回目 / 2回）</label><div class="answer-row"><input id="answerInput" value="${esc(attemptText)}" autocomplete="off" autocapitalize="off" inputmode="kana" placeholder="わからない時は空欄で確定"><button class="primary" data-action="answer">確定</button></div><p class="hint">空欄のまま確定すると、答えを表示します。</p>`:`<div class="feedback ${s.correct?'correct':'wrong'}">${s.correct?'○ 正解':'× 不正解'}　正答：${esc(accepted[0])}</div><div class="explanation"><h3>${esc(q.word)} <small>（${esc(q.reading)}）</small></h3><div class="metadata"><span class="tag">${esc(q.category)}</span>${(q.variants||[]).map(v=>`<span class="tag">異体・別表記 ${esc(v)}</span>`).join('')}</div><p>${esc(q.meaning)}</p></div><div class="quiz-tools"><button class="secondary" data-action="favorite">${state.favorites.includes(q.id)?'★ お気に入り':'☆ お気に入り'}</button><button class="primary" data-action="next">${s.index===s.ids.length-1?'結果を見る':'次の問題へ'}</button></div>`}</div></article></section>`;if(!s.answered)setTimeout(()=>document.querySelector('#answerInput')?.focus(),50)}
  function renderIdiomQuiz(){const s=state.session,q=current(),pct=((s.index+1)/s.ids.length)*100,choices=[...(s.part==="word"?q.wordChoices:q.meaningChoices)].sort(()=>Math.random()-.5),label=s.part==="word"?"（●●）に当てはまる二字を選択":"当てはまる意味を選択",prompt=s.part==="word"?q.prompt:q.word;let options=choices.map((c,i)=>"<button class=\"option-choice\" data-idiom-answer=\""+esc(c)+"\"><span>"+(s.part==="meaning"?i+1:"▽")+"</span>"+esc(c)+"</button>").join("");app.innerHTML="<section class=\"quiz-screen\"><div class=\"progress-head\"><span>第 "+(s.index+1)+" 問・"+(s.part==="word"?"熟語":"意味")+"</span><span>"+(s.index+1)+" / "+s.ids.length+"</span></div><div class=\"progress\"><span style=\"width:"+pct+"%\"></span></div><article class=\"paper-card\"><div class=\"question-label\">"+label+"</div><div class=\"question-word idiom-prompt\">"+esc(prompt)+"</div><div class=\"answer-area\">"+(!s.answered?"<div class=\"option-list\">"+options+"</div>":"<div class=\"feedback "+(s.correct?"correct":"wrong")+"\">"+(s.correct?"○ 正解":"× 不正解")+"　"+esc(q.word)+"</div><div class=\"explanation\"><h3>"+esc(q.word)+" <small>（"+esc(q.reading)+"）</small></h3><p>"+esc(q.meaning)+"</p></div><div class=\"quiz-tools\"><button class=\"secondary\" data-action=\"favorite\">"+(state.favorites.includes(q.id)?"★ お気に入り":"☆ お気に入り")+"</button><button class=\"primary\" data-action=\"next\">"+(s.index===s.ids.length-1?"結果を見る":"次の問題へ")+"</button></div>")+"</div></article></section>"}
  function answerIdiom(value){const s=state.session,q=current();if(s.part==="word"){s.wordCorrect=value===q.missing;s.part="meaning";save();renderIdiomQuiz();toast(s.wordCorrect?"二字は正解です":"正解は「"+q.missing+"」です");return}const meaningCorrect=value===q.meaningChoices[0];finishQuestion(Boolean(s.wordCorrect&&meaningCorrect),q.missing+"／"+value)}
  function submit(){const s=state.session,q=current(),input=document.querySelector('#answerInput');if(!s||!q)return;const answer=normalize(input.value);attemptText=input.value;const accepted=[q.reading,...(q.accepted||[])].map(normalize);if(answer&&accepted.includes(answer)){finishQuestion(true,answer);return}if(!answer){finishQuestion(false,'（スキップ）');return}s.attempts++;if(s.attempts>=2){finishQuestion(false,answer)}else{save();attemptText='';renderQuiz();toast('もう一度入力できます')}}
  function finishQuestion(correct,answer){const s=state.session,q=current();s.answered=true;s.correct=correct;s.answers.push({id:q.id,correct,answer});const old=state.progress[q.id]||{correct:0,wrong:0};state.progress[q.id]={correct:old.correct+(correct?1:0),wrong:old.wrong+(correct?0:1),weak:!correct,lastSeen:Date.now()};state.history.unshift({id:q.id,correct,answer,at:Date.now()});state.history=state.history.slice(0,100);save();attemptText='';renderQuiz()}
  function nextQuestion(){const s=state.session;if(s.index>=s.ids.length-1){route('result');return}s.index++;s.attempts=0;s.answered=false;s.correct=null;s.part='word';s.wordCorrect=null;save();renderQuiz()}
  function renderResult(){const s=state.session;if(!s){route('home');return}const answers=s.answers,correct=answers.filter(a=>a.correct).length,pct=Math.round(correct/answers.length*100)||0;app.innerHTML=`<section class="screen"><div class="result-hero"><p class="eyebrow">SESSION COMPLETE</p><div class="score-ring" style="--score:${pct}%"><b>${correct}/${answers.length}</b><span>正答率 ${pct}%</span></div><h1 class="section-title" style="margin:0">おつかれさまでした</h1></div>${answers.some(a=>!a.correct)?`<h2 class="section-title">間違えた問題</h2><div class="word-list">${answers.filter(a=>!a.correct).map(a=>wordItem(getAnyQ(a.id),a)).join('')}</div>`:'<div class="resume-card"><strong>全問正解です</strong><span>見事です。この調子で続けましょう。</span></div>'}<button class="primary wide start-button" data-action="finish">ホームへ戻る</button></section>`}
  function wordItem(q,record){if(!q)return'';const fav=state.favorites.includes(q.id);return `<article class="word-item" data-id="${q.id}"><div class="word-summary"><button class="star" data-favorite="${q.id}" aria-label="お気に入り">${fav?'★':'☆'}</button><button class="word-main" data-toggle="${q.id}" style="border:0;background:none;text-align:left"><b>${esc(q.word)}</b><span>${esc(q.reading)}</span></button>${record?`<span class="result-mark ${record.correct?'ok':'ng'}">${record.correct?'○':'×'}</span>`:'<span>⌄</span>'}</div><div class="word-detail"><div class="metadata"><span class="tag">${esc(q.category)}</span>${q.source==='study_note'?'<span class="tag">ノート由来</span>':''}${(q.variants||[]).map(v=>`<span class="tag">別表記 ${esc(v)}</span>`).join('')}</div><p>${esc(q.meaning)}</p><label class="hint">自分のメモ</label><textarea class="memo" data-memo="${q.id}" placeholder="覚え方や補足を入力">${esc(state.memos[q.id]||'')}</textarea></div></article>`}
  function renderList(type){const isHistory=type==='history';const title=isHistory?'過去問':'登録単語';app.innerHTML=`<section class="screen"><p class="eyebrow">${isHistory?'RECENT 100':'DICTIONARY'}</p><h1 class="section-title" style="font-size:27px;margin-top:0">${title}</h1><input class="search" id="searchInput" placeholder="漢字・読みから検索"><div class="filters">${!isHistory?'<button class="filter active" data-filter="all">すべて</button><button class="filter" data-filter="favorite">お気に入り</button><button class="filter" data-filter="weak">苦手</button><button class="filter" data-filter="unseen">未出題</button>':''}</div><div id="wordList" class="word-list"></div></section>`;updateList(type,'','all')}
  function updateList(type,query='',filter='all'){const n=normalize(query);let items=type==='history'?state.history.map(h=>({q:getAnyQ(h.id),r:h})):Q.map(q=>({q}));items=items.filter(({q})=>q&&(normalize(q.word).includes(n)||normalize(q.reading).includes(n)||(q.variants||[]).some(v=>normalize(v).includes(n))));if(type!=='history'){if(filter==='favorite')items=items.filter(x=>state.favorites.includes(x.q.id));if(filter==='weak')items=items.filter(x=>state.progress[x.q.id]?.weak);if(filter==='unseen')items=items.filter(x=>!state.progress[x.q.id])}document.querySelector('#wordList').innerHTML=items.length?items.map(x=>wordItem(x.q,x.r)).join(''):`<div class="empty">該当する単語はありません</div>`}
  function renderSettings(){app.innerHTML=`<section class="screen"><p class="eyebrow">OPTIONS</p><h1 class="section-title" style="font-size:27px;margin-top:0">オプション</h1><div class="panel"><div class="setting-row"><label>出題方法</label><p>次回の学習セットから反映されます。</p><div class="segmented"><button data-mode="random" class="${state.settings.mode==='random'?'active':''}">完全ランダム</button><button data-mode="priority" class="${state.settings.mode==='priority'?'active':''}">苦手・未出題優先</button></div></div><div class="setting-row"><label>出題の重み</label><p>通常 100 ／ 苦手 105 ／ 未出題 115</p></div><div class="setting-row"><label>この端末の学習データ</label><p>履歴・お気に入り・メモ・進行中の問題を消去します。</p><button class="danger" data-action="reset">学習データを消去</button></div></div></section>`}
  function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();toast(state.favorites.includes(id)?'お気に入りに追加しました':'お気に入りから外しました')}
  function showDiscard(){modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>途中の学習を終了しますか？</h2><p>現在の問題セットは削除されます。確定済みの回答履歴は残ります。</p><div class="modal-actions"><button class="secondary" data-modal="close">キャンセル</button><button class="danger" data-modal="discard">終了する</button></div></div></div>`}
  document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.route)route(t.dataset.route);if(t.dataset.count){selectedCount=Number(t.dataset.count);renderSetup()}if(t.dataset.mode){state.settings.mode=t.dataset.mode;save();render()}if(t.dataset.action==='setup'){selectedKind=t.dataset.kind||'reading';route('setup')};if(t.dataset.action==='start')newSession();if(t.dataset.action==='open-book')route('quiz');if(t.dataset.action==='answer')submit();if(t.dataset.idiomAnswer)answerIdiom(t.dataset.idiomAnswer);if(t.dataset.action==='next')nextQuestion();if(t.dataset.action==='resume')route('quiz');if(t.dataset.action==='discard'){state.session=null;save();render()}if(t.dataset.action==='favorite')toggleFavorite(current().id);if(t.dataset.action==='finish'){state.session=null;save();route('home')}if(t.dataset.action==='reset'){if(confirm('学習データをすべて消去しますか？')){localStorage.removeItem(KEY);state=structuredClone(defaults);route('home')}}if(t.dataset.favorite)toggleFavorite(t.dataset.favorite);if(t.dataset.toggle)t.closest('.word-item').classList.toggle('open');if(t.dataset.filter){document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===t));updateList(state.route,document.querySelector('#searchInput').value,t.dataset.filter)}if(t.dataset.modal==='close')modalRoot.innerHTML='';if(t.dataset.modal==='discard'){modalRoot.innerHTML='';state.session=null;save();route('home')}});
  document.addEventListener('input',e=>{if(e.target.id==='searchInput'){const active=document.querySelector('.filter.active');updateList(state.route,e.target.value,active?.dataset.filter||'all')}});
  document.addEventListener('change',e=>{if(e.target.dataset.memo){state.memos[e.target.dataset.memo]=e.target.value;save();toast('メモを保存しました')}});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='answerInput'){e.preventDefault();submit()}});
  backButton.addEventListener('click',()=>{if(state.route==='quiz'&&state.session){showDiscard();return}route('home')});brandButton.addEventListener('click',()=>route('home'));settingsButton.addEventListener('click',()=>route('settings'));
  render();
})();
